service: nest-cart-api



plugins:
 - 'serverless-plugin-typescript'
 - serverless-offline
 - serverless-dotenv-plugin

useDotenv: true

provider:
 name: aws
 runtime: nodejs14.x
 region: 'us-east-1'

functions:
 main: # The name of the lambda function
   # The module 'handler' is exported in the file 'src/lambda'
   handler: src/lambda.handler
   events:
     - http:
         method: any
         path: /{any+}